Revert "run-tests with jvmti-stress configuration"
I couldn't find a proper way to resolve the dependencies. Therefore
let's use a workaround until we'll stumble across the solution one day.

Revert several changes related to commit: 8f2c6d479aeda3165c4f54c1076ec7ac335fccc7.

This change will allow to skip the following compiler error:
  error: art/test/Android.bp:364:1: "libtistress" depends on undefined module "slicer"
  error: art/test/Android.bp:370:1: "libtistressd" depends on undefined module "slicer"

Signed-off-by: spezi77 <spezi7713@gmx.net>